version: '3'

services:
  web:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "20000:80"
    links:
      - php

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    links:
      - admin

  admin:
    build:
      context: .
      dockerfile: docker/admin/Dockerfile
