version: '3.7'

services:
  calculator:
    build: .
    read_only: true
    deploy:
      mode: replicated
      replicas: 3
      resources:
        limits:
          cpus: "0.2"
          memory: 200M
      restart_policy:
        condition: on-failure
    networks:
      - no-outbound
    dns: "127.0.0.1"

  web:
    image: nginx:alpine
    restart: on-failure
    networks:
      - internal
      - no-outbound
    ports:
      - 10011:80
    depends_on:
      - calculator
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

networks:
  no-outbound:
    driver: bridge
    internal: true
  internal:
    driver: bridge
