version: '3.2'
services:
  jointspay-app:
    build:
      context: .
      dockerfile: Dockerfile.app
    image: server_jointspay-app
    restart: on-failure
    networks:
      - jointspay-network

  jointspay-nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    image: server_jointspay-nginx
    restart: on-failure
    ports:
      - "10001:80"
    networks:
      - jointspay-network

  jointspay-selenium:
    build:
      context: .
      dockerfile: Dockerfile.selenium
    image: server_jointspay-selenium
    restart: on-failure
    networks:
      - jointspay-network

networks:
  jointspay-network:
    driver: overlay
    attachable: true
